version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    restart: always
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    user: root
    restart: always
